# By m7wq

# Database
DATABASE:
  driver: "jdbc:mysql://"
  host: "localhost"
  port: 3306
  username: "root"
  password: ""
  database: "test_database"
  databaseProperties: "?useSSL=false&serverTimezone=UTC"
  maximumPoolSize: 10

# Currently roles are MASTER, ADMIN, MODERATOR, SPECIAL, MEMBER
# ill make it changeable soon!
# make sure that they are on upper case

permissions:
  can-invite:
    - MASTER
    - ADMIN
    - MODERATOR
  can-mute:
    - MASTER
    - ADMIN
  can-kick:
    - MASTER
  can-promote:
    - MASTER
    - ADMIN
  can-demote:
    - MASTER
    - ADMIN

# Game options
options:
  # Time that system take to remove the invitation
  expire-time: 30 # seconds
  # Messages main prefix
  prefix: "&3&lGUILDS &8┃"


tag:
  format: "%color%[%tag%]"
  # Default tag color when guild get creating
  default-tag-color: "&f"

guild:
  not-found-guild: "&aNo Guild"
  not-found-role: "&aNo Role"