# By m7wq

# Database
DATABASE:
  driver: "jdbc:mysql://"
  host: "localhost"
  port: 3306
  username: "root"
  password: ""
  database: "test_database"
  databaseProperties: "?useSSL=false&serverTimezone=UTC"
  maximumPoolSize: 10

# Game options
options:
  # Messages main prefix
  prefix: "&3&lGUILDS &8┃"
  # Selecting time that when it over you need to re confirm
  selecting-time: 5 # seconds

tag:
  # Default tag color when guild get creating
  default-tag-color: "&f"