# =========================================
#            qGuilds Plugin
# =========================================
# Author: m7wq
# Description: Free customized guilds plugin
# Open Source Plugin.
# =========================================

# ============ DATABASE ============

# Database connection settings for the application.
DATABASE:
  enabled: true # false -> use SQLITE
  driver: "jdbc:mysql://"  # JDBC driver for the database connection (Don't change if you don't understand)
  host: "127.0.0.1"  # Database host (localhost in this case)
  port: 3306  # Database port
  username: "username"  # Username to access the database
  password: "password"  # Password to access the database
  database: "database"  # Database name
  databaseProperties: "?useSSL=false&serverTimezone=UTC"  # Database properties for connection
  maximumPoolSize: 10  # Maximum number of database connections in the pool

# ============ DATABASE ============

# ============ ROLES ============
    # System Permissions
    #can-invite
    #can-mute
    #can-unMute
    #can-kick
    #can-promote
    #can-demote
    #can-setTag
    #can-setTagColor
    #can-rename
    #can-setRole
    #can_editRoles ~ new permission!
# Default roles (on creating)
# Role Name_Role_Permissions List color ("_" between them)
# Example Mod_&c_can-mute,can-kick

# -- ORDER IS IMPORTANT --
default-roles:
  # Low Roles

  - Member_&9

  - Master_&e_ 
    can_setRole,
    can-invite,
    can-mute,
    can-unMute,
    can-kick,
    can-promote,
    can-demote,
    can-setTag,
    can-setTagColor,
    can-rename,
    can-editRoles

  # High roles

# ============ ROLES ============

# ============ COOLDOWNS ============

# Define cooldowns for various actions in days or hours.
cooldowns:
  enabled: false
  settag: 2  # Days
  rename: 7  # Days
  create: 5  # Days
  settagcolor: 12  # Hours

# ============ COOLDOWNS ============

# ============ PERMISSIONS ============

# Permissions that control who can perform certain actions in the guild system.
permissions:
  allow-to-see-list-of-other-guilds: true  # Allow players to see other guilds' lists

# ============ PERMISSIONS ============

# ============ GAME OPTIONS ============

# Game-related configuration options.
options:
  expire-time: 30  # Time in seconds before an invitation request expires
  prefix: "&3&lGUILDS &8〢"  # Prefix for messages


# ============ GAME OPTIONS ============

# ============ TAG CONFIGURATION ============

# Configuration for guild tags.
tag:
  format: "%color%[%tag%]"  # Format for the guild tag (with color support)
  default-tag-color: "&f"  # Default color for the guild tag when the guild is created
  default-tag: "" # Default tag when no tag is set

# ============ TAG CONFIGURATION ============
